/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicShopConfigRouteImport } from './routes/api/public/shop-config'
import { Route as ApiPublicRachidaChatRouteImport } from './routes/api/public/rachida-chat'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopConfigRoute = ApiPublicShopConfigRouteImport.update({
  id: '/api/public/shop-config',
  path: '/api/public/shop-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRachidaChatRoute = ApiPublicRachidaChatRouteImport.update({
  id: '/api/public/rachida-chat',
  path: '/api/public/rachida-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/rachida-chat': typeof ApiPublicRachidaChatRoute
  '/api/public/shop-config': typeof ApiPublicShopConfigRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/rachida-chat': typeof ApiPublicRachidaChatRoute
  '/api/public/shop-config': typeof ApiPublicShopConfigRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/rachida-chat': typeof ApiPublicRachidaChatRoute
  '/api/public/shop-config': typeof ApiPublicShopConfigRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/public/rachida-chat'
    | '/api/public/shop-config'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/api/public/rachida-chat' | '/api/public/shop-config'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/api/public/rachida-chat'
    | '/api/public/shop-config'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ApiPublicRachidaChatRoute: typeof ApiPublicRachidaChatRoute
  ApiPublicShopConfigRoute: typeof ApiPublicShopConfigRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shop-config': {
      id: '/api/public/shop-config'
      path: '/api/public/shop-config'
      fullPath: '/api/public/shop-config'
      preLoaderRoute: typeof ApiPublicShopConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rachida-chat': {
      id: '/api/public/rachida-chat'
      path: '/api/public/rachida-chat'
      fullPath: '/api/public/rachida-chat'
      preLoaderRoute: typeof ApiPublicRachidaChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ApiPublicRachidaChatRoute: ApiPublicRachidaChatRoute,
  ApiPublicShopConfigRoute: ApiPublicShopConfigRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
