/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicShopConfigRouteImport } from './routes/api/public/shop-config'
import { Route as ApiPublicRachidaVisionRouteImport } from './routes/api/public/rachida-vision'
import { Route as ApiPublicRachidaSearchRouteImport } from './routes/api/public/rachida-search'
import { Route as ApiPublicRachidaChatRouteImport } from './routes/api/public/rachida-chat'
import { Route as ApiPublicHooksDailyReportRouteImport } from './routes/api/public/hooks/daily-report'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopConfigRoute = ApiPublicShopConfigRouteImport.update({
  id: '/api/public/shop-config',
  path: '/api/public/shop-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRachidaVisionRoute = ApiPublicRachidaVisionRouteImport.update({
  id: '/api/public/rachida-vision',
  path: '/api/public/rachida-vision',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRachidaSearchRoute = ApiPublicRachidaSearchRouteImport.update({
  id: '/api/public/rachida-search',
  path: '/api/public/rachida-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRachidaChatRoute = ApiPublicRachidaChatRouteImport.update({
  id: '/api/public/rachida-chat',
  path: '/api/public/rachida-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDailyReportRoute =
  ApiPublicHooksDailyReportRouteImport.update({
    id: '/api/public/hooks/daily-report',
    path: '/api/public/hooks/daily-report',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/api/public/rachida-chat': typeof ApiPublicRachidaChatRoute
  '/api/public/rachida-search': typeof ApiPublicRachidaSearchRoute
  '/api/public/rachida-vision': typeof ApiPublicRachidaVisionRoute
  '/api/public/shop-config': typeof ApiPublicShopConfigRoute
  '/api/public/hooks/daily-report': typeof ApiPublicHooksDailyReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/api/public/rachida-chat': typeof ApiPublicRachidaChatRoute
  '/api/public/rachida-search': typeof ApiPublicRachidaSearchRoute
  '/api/public/rachida-vision': typeof ApiPublicRachidaVisionRoute
  '/api/public/shop-config': typeof ApiPublicShopConfigRoute
  '/api/public/hooks/daily-report': typeof ApiPublicHooksDailyReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/api/public/rachida-chat': typeof ApiPublicRachidaChatRoute
  '/api/public/rachida-search': typeof ApiPublicRachidaSearchRoute
  '/api/public/rachida-vision': typeof ApiPublicRachidaVisionRoute
  '/api/public/shop-config': typeof ApiPublicShopConfigRoute
  '/api/public/hooks/daily-report': typeof ApiPublicHooksDailyReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/api/public/rachida-chat'
    | '/api/public/rachida-search'
    | '/api/public/rachida-vision'
    | '/api/public/shop-config'
    | '/api/public/hooks/daily-report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/api/public/rachida-chat'
    | '/api/public/rachida-search'
    | '/api/public/rachida-vision'
    | '/api/public/shop-config'
    | '/api/public/hooks/daily-report'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/api/public/rachida-chat'
    | '/api/public/rachida-search'
    | '/api/public/rachida-vision'
    | '/api/public/shop-config'
    | '/api/public/hooks/daily-report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ApiPublicRachidaChatRoute: typeof ApiPublicRachidaChatRoute
  ApiPublicRachidaSearchRoute: typeof ApiPublicRachidaSearchRoute
  ApiPublicRachidaVisionRoute: typeof ApiPublicRachidaVisionRoute
  ApiPublicShopConfigRoute: typeof ApiPublicShopConfigRoute
  ApiPublicHooksDailyReportRoute: typeof ApiPublicHooksDailyReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shop-config': {
      id: '/api/public/shop-config'
      path: '/api/public/shop-config'
      fullPath: '/api/public/shop-config'
      preLoaderRoute: typeof ApiPublicShopConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rachida-vision': {
      id: '/api/public/rachida-vision'
      path: '/api/public/rachida-vision'
      fullPath: '/api/public/rachida-vision'
      preLoaderRoute: typeof ApiPublicRachidaVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rachida-search': {
      id: '/api/public/rachida-search'
      path: '/api/public/rachida-search'
      fullPath: '/api/public/rachida-search'
      preLoaderRoute: typeof ApiPublicRachidaSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rachida-chat': {
      id: '/api/public/rachida-chat'
      path: '/api/public/rachida-chat'
      fullPath: '/api/public/rachida-chat'
      preLoaderRoute: typeof ApiPublicRachidaChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-report': {
      id: '/api/public/hooks/daily-report'
      path: '/api/public/hooks/daily-report'
      fullPath: '/api/public/hooks/daily-report'
      preLoaderRoute: typeof ApiPublicHooksDailyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ApiPublicRachidaChatRoute: ApiPublicRachidaChatRoute,
  ApiPublicRachidaSearchRoute: ApiPublicRachidaSearchRoute,
  ApiPublicRachidaVisionRoute: ApiPublicRachidaVisionRoute,
  ApiPublicShopConfigRoute: ApiPublicShopConfigRoute,
  ApiPublicHooksDailyReportRoute: ApiPublicHooksDailyReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
